# Generated by Django 4.1.5 on 2023-01-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('authorized', 'authorized'), ('initiated', 'initiated'), ('successful', 'successful'), ('returned', 'returned'), ('canceled', 'canceled')], default='initiated', max_length=20)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('swifter_id', models.CharField(max_length=20, unique=True)),
                ('external_id', models.CharField(max_length=20, unique=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
